# Thermal Imagery Data

On July 5, 2020, [NV5 Geospatial](https://www.nv5.com/geospatial/) collected thermal infrared imagery from a helicopter-mounted camera for four steams on the Kenai Peninsula in southern Alaska. These streams included:

-   Kenai River Tributaries

    -   Beaver Creek

    -   Funny River

    -   Moose River

-   Kasilof River Tributary

    -   Crooked Creek

All streams were flown during the afternoon hours in order to maximize the thermal contrast between the river's water and the banks.

The surveys extend for a total length of 59.1 km of the streams, covering upstream extents from their outlets at the Kenai or Kasilof rivers. The data were collected to aid the team in identifying the spatial variability in surface temperatures as well as thermal influence of point sources, tributaries, and surface springs.

Specific deliverables generated by NV5 Geospatial from the thermal imagery data include:

-   Rasters (map image files; .tif and .jpg formats)

-   Shapefiles (longitudinal temperature profiles, stream centerlines, others; .shp format)

-   Other supplemental items (coordinates of significant thermal features, maps and figures, and others)

The full technical report from NV5 Geospatial describing detailed methods and interpretation can be accessed at the following link:

-   [Kenai Rivers Thermal Infrared Airborne Imagery Technical Data Report (NV5 Geospatial)](https://github.com/Kenai-Watershed-Forum/kenai_river_thermal_imagery/blob/master/documents/TIR_Technical_Data_Report_Kenai_Rivers_20210107.pdf "Link")

The image raster files are of a large size (\~3 GB) and may be acquired by contacting staff at Cook Inletkeeper, Kenai Watershed Forum, or Kachemak Heritage Land Trust.

<br>




